### ISSUE TITLE
RVIZ Visual tools GUI Does not appear

### ISSUE THREAD

**Issue by amirhm64** [ros-planning/moveit_tutorials#107]
Hi I am trying to use the movegroup interface tutorial on my own robot but I get this warning while running it 

      _Topic '/rviz_visual_tools' unable to connect to any subscribers within 0.5 sec. It is possible initially published visual messages will be lost._

and also on rviz side I cant see the rvizvisualtoolsgui to click next. On PR2 It runs perfectly.
I am running kinetic

**Comment by amirhm64** [comment]
Had to add a new pannel in rviz

**Comment by WwYyFan** [comment]
@amirhm64  Hello, I could not found a pannel name "RvizVisualToolsGui" in rviz, how to fix it?

**Comment by amirhm64** [comment]
> @amirhm64 Hello, I could not found a pannel name "RvizVisualToolsGui" in rviz, how to fix it?

you can go to panels>add new panel

**Comment by stevewen** [comment]
@amirhm64 I have added the new pannel in rviz, but it  doesn't work, the warning still appear.

**Comment by shd01x** [comment]
In case anyone's google leads here, you need to add a new rviz MarkerArray display, and make sure that the MarkerArray is subscribing to the topic that the markers are published on (that topic is a parameter to the MoveIt visual tools constructor in your C++ file).  If your setup is like mine, you might also need to add a delay of a few seconds before publishing so that Rviz has time to initialize.

**Comment by SeanHRI** [comment]
You may first check whether there RvizVisualToolGui is. If not, I think you can solve this issue by typing "_sudo apt-get install ros-[distro]-rviz-visual-tools_" in your terminal.
