### ISSUE TITLE
No motion plan found. No execution attempted

### ISSUE THREAD

**Issue by RYANZYC** [ros-planning/moveit_tutorials#334]
My robotic arm is a yumi7 DOF dual-arm robot. I fixed his 6 and 7 joints into 5 degrees of freedom. I modified the urdf file and the srdf file. I modified the group to make link6 its end executor. I can use setjointvaluetarget function, but I can't use setposetarget function. This error will occur  " Fail: ABORTED: No motion plan found. No execution attempted" . The ball inside rviz can't be dragged either.

**Comment by rhaschke** [comment]
Please pose such questions on ros.answers.org. This is not an issue of MoveIt or the tutorials.
Why do you want to limit your 7-DoF arm to 5-DoF only?? A 5-DoF arm can only reach a tiny subset of all Cartesian end-effector poses, which is why inverse kinematics fails (you cannot "drag the ball in rviz").
