### ISSUE TITLE
2 Franka Emika Panda working simultaneously 

### ISSUE THREAD

**Issue by pkr97** [ros-planning/moveit_tutorials#442]
### Description

How to use 2 Franka Emika Panda robots simultaneously?
 
### Your environment
* ROS Distro: Melodic
* OS Version:  Ubuntu 18.04

I'm a beginner with Moveit and motion planning inside ROS.

I found these Moveit tutorials very helpful but sometimes we need multiple robots for coordinated manipulation. That needs path planning, collision avoidance, and the safety of manipulators as well as humans.

I was wondering is there exists a way to use 2 or more manipulators simultaneously inside Moveit.

It would be great if anyone could put some light on this subject.

Thanks...

**Comment by rhaschke** [comment]
This question should be better asked at https://answers.ros.org. Please, post real issues and bug reports here.
MoveIt can only deal with a single robot description. Thus, to handle several robots, you need to combine them in a single URDF and provide a single, matching SRDF. The two sub robots should get individual move groups so that they still can be used independently from each other. However, planning coherent motions typically involves planning in the joined configuration spaces of both robots, which scales poorly.
