### ISSUE TITLE
Please update STOMP planner documentation

### ISSUE THREAD

**Issue by MichalDobis** [ros-planning/moveit_tutorials#681]
The stomp_core and the stomp_moveit has been split into two separe packages in pull request [882784c](https://github.com/ros-industrial/stomp_ros/commit/882784c6952e6456c85d0f61686913a33309bcfe)

Please, update documentation in https://ros-planning.github.io/moveit_tutorials/doc/stomp_planner/stomp_planner_tutorial.html section Prerequisites step 3. Now both packages are required https://github.com/ros-industrial/stomp_ros and https://github.com/ros-industrial/stomp

**Comment by rhaschke** [comment]
You are welcome to file a PR :wink:

**Comment by MichalDobis** [comment]
Ok, I suggest this PR: https://github.com/ros-planning/moveit_tutorials/pull/683

**Comment by mamariomiamo** [comment]
Number 3 in the prerequisite lists seems to be redundant if the user follow the Installing STOMP from source. Since we need both stomp and stomp_ros packages, I believe it is more accurate to differentiate the name when using wstool set as when I followed the current documentation, it led to build errors.

In fact, stomp_ros's dependencies.rosintall lists the stomp as well as ros_industrial_cke_boilerplate so we can add that into the documentation. I suggest this PR: https://github.com/ros-planning/moveit_tutorials/pull/700

**Comment by LAbron665** [comment]
I have the error below when following the current STOMP planner tutorial.
![image](https://user-images.githubusercontent.com/90312932/152673696-d34cd52d-5e52-48ba-b56b-d66b98b12215.png)

**Comment by rhaschke** [comment]
Addressed in #683.
